FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN addgroup -S app && adduser -S app -G app && chown -R app:app /app

USER app

EXPOSE 3000

CMD ["npm", "start"]
